name: deploy-expiration

on:
  push:
    branches: [master]
    paths: [expiration/**]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: cd expiration && docker build -t agreeloren106001/ticketing-expiration .
      - name: Login in DockerHub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the image to DockerHub
        run: docker push agreeloren106001/ticketing-expiration
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Get the kubenetes config file and set context
        run: doctl kubernetes cluster kubeconfig save ticketing
      - name: Re-deploy the service
        run: kubectl rollout restart deployment expiration-depl
