name: deploy-tickets

on:
  push:
    branches: [master]
    paths: [tickets/**]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: cd tickets && docker build -t agreeloren106001/ticketing-tickets .
      - name: Login in DockerHub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the image to DockerHub
        run: docker push agreeloren106001/ticketing-tickets
