name: deploy-manifests

on:
  push:
    branches: [master]
    paths: [infra/**]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Get the kubenetes config file and set context
        run: doctl kubernetes cluster kubeconfig save ticketing
      - name: Apply the manifests
        run: kubectl apply -f infra/k8s
